### PREFIX #####

unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### TERMINAL #####

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -ga terminal-overrides ",*:Tc"

##### GENERAL #####

set -g mouse on

set -g history-limit 100000

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set -g detach-on-destroy off

set -g escape-time 0

set -g status-left "#[bold]#S  "

##### COPY MODE (VIM) #####

setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

##### SPLITS #####

bind c new-window -c "#{pane_current_path}"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

##### PANE NAVIGATION #####

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### RESIZE #####

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### WINDOW NAMES #####

set -g allow-rename off
set -g automatic-rename off

##### RELOAD #####

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

##### TPM PLUGINS #####

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'


##### CONTINUUM #####

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

##### CATPPUCCIN #####

set -g @catppuccin_flavor 'mocha'

# Показывать имя окна (#W), а не title (#T)
set -g @catppuccin_window_text "#I:#W"
set -g @catppuccin_window_current_text "#I:#W"

# Модули справа
set -g @catppuccin_status_modules_right "directory session date_time"

# Формат времени
set -g @catppuccin_date_time "%H:%M"

##### TPM INIT #####

run '~/.config/tmux/plugins/tpm/tpm'
